### ISSUE TITLE
뷰 페이저 필요

### ISSUE THREAD

**Issue by Zi-Yun** [Nexters/LastWednesday#3]
메인액티비티에 적용할 뷰 페이저 필요합니다
티켓북, 메인, 히스토리 세 개 페이지 필요해요 
애니메이션 없이 부탁드립니다.

**Comment by hyunsikshin** [comment]
뷰페이저에 검색은 없는거죠? 0 티켓북 1 메인 2 히스토리?

**Comment by Zi-Yun** [comment]
네네 ! 수정했어요

**Comment by Zi-Yun** [comment]
#4 resolve
